name: Playwright CI/CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    name: Run Playwright Tests on Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Setup Node.js
        uses: actions/setup-node@latest
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start Next.js server
        run: npm run start &
        env:
          NODE_ENV: production

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@latest
        with:
          name: playwright-report
          path: playwright-report/
